### ISSUE TITLE
Get tests working on TravisCI

### ISSUE THREAD

**Issue by JacobFischer** [JacobFischer/netlinkwrapper#7]
`npm test` does not work currently on TravisCI.

On my linux box and macbook they work fine. However on the same macbook in Windows it fails with the same error as travis (server doesn't start).

This is not a version 1.1.1 issue, as the same is true in version 1.1.0. I just need to give the tests some TLC.

**Comment by basti1302** [comment]
In my experience Travis can be really slow sometimes, maybe it's enough to increase the timeouts a lot. Doesn't explain the failure in Windows, though.

**Comment by JacobFischer** [comment]
Thanks to #9 this is working in Travis [finally] again. Thanks!
